In [11]:
import numpy as np
from edunets.tensor import Tensor

x = Tensor([[2.0, 3.0], [-2.0, 1.0]], requires_grad=True)
y = Tensor([[2.0, 5.0], [0.0, -2.0]], requires_grad=True)
w = x @ y
print(w)
z = w.min()
print(z)
z.backward()

print(20*'-')
print(x.grad)  # dz/dx
print(y.grad)  # dz/dy

tensor([[  4.,   4.],
       [ -4., -12.]], dtype=float32, requires_grad=True)
tensor(-12., dtype=float32, requires_grad=True)
--------------------
[[ 0.  0.]
 [ 5. -2.]]
[[ 0. -2.]
 [ 0.  1.]]


In [12]:
import torch

x = torch.tensor([[2.0, 3.0], [-2.0, 1.0]], requires_grad=True)
y = torch.tensor([[2.0, 5.0], [0.0, -2.0]], requires_grad=True)
w = x @ y
print(w)
z = w.min()
z.backward()

print(20*'-')
print(x.grad)  # dz/dx
print(y.grad)  # dz/dy

tensor([[  4.,   4.],
        [ -4., -12.]], grad_fn=<MmBackward>)
--------------------
tensor([[ 0.,  0.],
        [ 5., -2.]])
tensor([[ 0., -2.],
        [ 0.,  1.]])
