In [1]:
import numpy as np
from edunets.tensor import Tensor

x = Tensor.eye(3, requires_grad=True)
y = Tensor([[2.0,0,-2.0]], requires_grad=True)
w = y * x
print(w)
z = w.sum()
z.backward()

print(20*'-')
print(x.grad)  # dz/dx
print(y.grad)  # dz/dy

tensor([[ 2.,  0., -0.],
       [ 0.,  0., -0.],
       [ 0.,  0., -2.]], dtype=float32, requires_grad=True)
[[ 2.  0. -2.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
