In [1]:
%pylab inline
import torch
import numpy as np
from tqdm import trange

from edunets.nn import Linear
from edunets.tensor import Tensor
from edunets.functions import argmax
np.set_printoptions(suppress=True)

Populating the interactive namespace from numpy and matplotlib


In [2]:
l_edunets = [Tensor.uniform(2,2) for _ in range(5)]
l_torch = [torch.tensor(el.data) for el in l_edunets]
l_edunets

[tensor([[-0.51904374, -0.8812343 ],
        [ 0.8981719 ,  0.25916117]], dtype=float32),
 tensor([[ 0.9073209 , -0.6314076 ],
        [-0.37948886,  0.04136591]], dtype=float32),
 tensor([[ 0.730488  ,  0.75895995],
        [-0.58962727, -0.52425855]], dtype=float32),
 tensor([[ 0.86998904, -0.460693  ],
        [ 0.66686076, -0.3661649 ]], dtype=float32),
 tensor([[-0.39734963,  0.805009  ],
        [-0.509032  , -0.3151649 ]], dtype=float32)]

In [17]:
sum(l_edunets),  torch.stack(l_torch, dim=0).sum(dim=0)

(tensor([[-1.2552814 , -0.5714249 ],
        [-0.23605426,  1.2299877 ]], dtype=float32),
 tensor([[-1.2553, -0.5714],
         [-0.2361,  1.2300]]))

In [7]:
T1 = torch.rand(2,3,3, requires_grad=True)
T2 = torch.rand(2, 3, 3)

T1 == T2

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False]],

        [[False, False, False],
         [False, False, False],
         [False, False, False]]])

In [4]:
T1 = Tensor.eye(3, requires_grad=True)
T2 = Tensor.eye(3)
T3 = T1 @ T2 + T1
T4 = T3.sum()

T4.backward()
print(T3._key)

T1 = torch.tensor(T1.data, requires_grad=True)
T2 = torch.tensor(T2.data)
T3 = T1 @ T2 + T1
T4 = T3.sum()

T4.backward()
print(T1.grad)

4178282173
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [7]:
T1 = torch.zeros(3, 3, requires_grad=True)
T1.grad = torch.zeros(3, 3)
T1

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)

In [11]:
l = [t for t in T1]

T1.max().backward()

l[0].grad

RuntimeError: grad can be implicitly created only for scalar outputs